"""last changes

Revision ID: 42013893db83
Revises: cd178b819c63
Create Date: 2022-05-12 22:33:35.140615

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '42013893db83'
down_revision = 'cd178b819c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('meals', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
