"""add order table

Revision ID: 6b2ca91c7e42
Revises: 2061d1abb7db
Create Date: 2022-05-21 20:37:27.142115

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6b2ca91c7e42'
down_revision = '2061d1abb7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_amount', sa.Float(), nullable=True),
                    sa.Column('order_status', sa.String(), nullable=True),
                    sa.Column('order_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_details',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['product_id'], ['meals.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users',
                  sa.Column('balance', sa.INTEGER(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('orders')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
